---
collections:
  - name: https://github.com/companieshouse/ansible-collections.git#/ch_collections/base/
    type: git
    version: 0.1.35

roles:
  - src: https://github.com/geerlingguy/ansible-role-repo-epel
    name: epel
    version: "1.3.0"

